<div class="menu">
    <div class="menu__column">
        <h4><?php echo __('Categoryes')?><span class="menu__column--icon">+</span></h4>
        <ul>
            <li><a href="#"><?php echo __('Outdoor Lounges')?></a></li>
            <li><a href="#"><?php echo __('Outdoor Dining')?></a></li>
            <li><a href="#"><?php echo __('Outdoor Umbrellas & Accessories')?></a></li>
            <li><a href="#"><?php echo __('Wood Fireplaces')?></a></li>
            <li><a href="#"><?php echo __('Ethanol Fireplaces')?></a></li>
            <li><a href="#"><?php echo __('Electric Fireplaces')?></a></li>
            <li><a href="#"><?php echo __('Weber Charcoal BBQs')?></a></li>
            <li><a href="#"><?php echo __('Weber Premium Gas BBQs')?></a></li>
            <li><a href="#"><?php echo __('Weber Qs')?></a></li>
            <li><a href="#"><?php echo __('Weber Electric BBQs')?></a></li>
            <li><a href="#"><?php echo __('Clearance Store')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Why Burning Log')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('About us')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('All products')?></a></li>
            <li><a href="#" id="open-map" title="<?php echo __('Contact Us')?>"><?php echo __('Catalogues')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Contact us')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Our Policies')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('Terms and conditions')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Return policy')?></a></li>
            <li><a href="#" id="open-map" title="<?php echo __('Contact Us')?>"><?php echo __('Delivery and pick up policy')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Privacy policy')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Newsletter')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('Subscribe to our newsletter for the latest')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('news and updates')?></a></li>
            <li>
                <i class="menu__inputicon fas fa-angle-right"></i>
                <input type="text" class="footer--newletter__input" placeholder="Enter your email address">
            </li>
            <li>
                <div class="menu__listicon">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                    <a href="#"><i class="fab fa-pinterest"></i></a>
                </div>
            </li>
        </ul>
    </div>
</div>