<div class="footer--bottom">
    <!-- <div class="copyright">
        <span class="copyright__text">© 2018 Burning Log. All rights reserved</span>
    </div> -->
    <div class="footer--bottom__icon">
    <a href="#home">
        <img
        width="90"
        height="40"
        src="<?php echo $block->getViewFileUrl('images/eway.jpg'); ?>"
        alt="Website Eway"
        />
    </a>
    <a href="#news">
        <img
        src="<?php echo $block->getViewFileUrl('images/master.jpg'); ?>"
        alt="Website Master"
        />
    </a>
    <a href="#contact">
        <img
        src="<?php echo $block->getViewFileUrl('images/paypal.jpg'); ?>"
        alt="Website Paypal"
        />
    </a>
    <a href="#about">
        <img
        src="<?php echo $block->getViewFileUrl('images/shape.jpg'); ?>"
        alt="Website Shape"
        />
    </a>
    <a href="#about">
        <img
        src="<?php echo $block->getViewFileUrl('images/visa.jpg'); ?>"
        alt="Website Visa"
        />
    </a>
    </div>
</div>