<div class="footer--top">
    <div class="footer--top__column">
        <a href="#" class="footer--top__item">We ship australia wide!</a>
    </div>
    <div class="footer--top__column">
        <a href="#" class="footer--top__item">Find a store</a>
    </div>
    <div class="footer--top__column">
        <a href="#" class="footer--top__item">Money back guarantee</a>
    </div>
    <div class="footer--top__column">
        <a href="#" class="footer--top__item">Contact us</a>
    </div>
</div>